CREATE DATABASE IF NOT EXISTS CoronaMap_DB;
USE CoronaMap_DB;

CREATE TABLE IF NOT EXISTS api_keys(
    NAME VARCHAR(100) NOT NULL,
    APIKEY VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS infected_people(

);

CREATE TABLE IF NOT EXISTS clinic_location(

);


CREATE TABLE IF NOT EXISTS mask_info_board(
int(10) id NOT NULL,
 
);